//! 构建期代码生成：从唯一真源 `dangerous-commands.json` 读取危险命令短语，
//! 生成 `dangerous_commands.gen.rs` 供 `sandbox.rs` 的 `DangerousCommands::defaults()` 消费。
//!
//! 这样 Rust 内核与 TS 适配器共用同一份定义，杜绝「双表各自维护、语义分叉」的腐化
//! （审计 §5 项 #18）。规则只改 JSON，绝不同时手写两份。

use std::env;
use std::fs;
use std::path::PathBuf;

/// 仓库内唯一真源路径：crates/omni-core -> 仓库根/src/adapters/sandbox/dangerous-commands.json
fn source_json() -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .join("..")
        .join("..")
        .join("src")
        .join("adapters")
        .join("sandbox")
        .join("dangerous-commands.json")
}

fn main() {
    let json_path = source_json();
    let content = fs::read_to_string(&json_path)
        .unwrap_or_else(|e| panic!("无法读取唯一真源危险命令表 {:?}: {}", json_path, e));

    // 用 Value 解析，忽略 comment 等附加字段，只取 patterns 数组。
    let parsed: serde_json::Value = serde_json::from_str(&content)
        .unwrap_or_else(|e| panic!("危险命令表 JSON 解析失败: {}", e));
    let patterns = parsed["patterns"]
        .as_array()
        .expect("危险命令表必须包含 patterns 数组");

    let mut out = String::new();
    out.push_str("// @generated by build.rs from dangerous-commands.json — 勿手改。\n");
    out.push_str("/// 危险命令短语（规范化子串、大小写不敏感）。来源：dangerous-commands.json。\n");
    out.push_str("pub const DANGEROUS_COMMAND_PATTERNS: &[&str] = &[\n");
    for p in patterns {
        let s = p
            .as_str()
            .expect("patterns 的每个元素必须是字符串");
        // 转义双引号与反斜杠，保证生成的 Rust 字面量合法。
        let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
        out.push_str(&format!("    \"{}\",\n", escaped));
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR 未设置（构建脚本应在 cargo 环境下运行）"));
    let out_path = out_dir.join("dangerous_commands.gen.rs");
    fs::write(&out_path, out).unwrap_or_else(|e| panic!("写入生成文件失败: {}", e));

    // 唯一真源变化时重跑本构建脚本。
    println!("cargo:rerun-if-changed={}", json_path.display());
}
